const stockSymbols = [
    [{"Amazon": "AMZN"}],
    [{"American Airlines": "AAL"}],
    [{"Activision Blizzard": "ATVI"}],
    [{"Apple": "AAPL"}],
    [{"Alibaba Group": "BABA"}],
    [{"Electronic Arts": "EA"}],
    [{"eBay": "EBAY"}],
    [{"Facebook": "FB"}],
    [{"Alphabet": "GOOGL"}],
    [{"Hewlett Packard": "HPE"}],
    [{"Intel": "INTC"}],
    [{"Coca-cola": "KO"}],
    [{"MasterCard": "MA"}],
    [{"McDonalds": "MCD"}],
    [{"Microsoft": "MSFT"}],
    [{"Netflix": "NFLX"}],
    [{"Nike": "NKE"}],
    [{"NVIDIA": "NCDA"}],
    [{"New York Times": "NYT"}],
    [{"Oracle": "ORCL"}],
    [{"Pitnerest": "PINS"}],
    [{"Paypal": "PYPL"}],
    [{"Starbucks": "SBUX"}],
    [{"Sony": "SNEJF"}],
    [{"Spotify": "SPOT"}],
    [{"Tesla": "TSLA"}],
    [{"Twitter": "TWTR"}]
];

export default stockSymbols;